What is the most famous recipe from {stateOrCountry}? Response in JSON without markdown tags with the name of the recipe in a property named `recipe`.
The name of the recipe in a property named `name` inside the object recipe.
Each ingredient must be in a property named `ingredient`.
List every step in a property named `steps`.
The cooking time of the recipe must be indicated in a property named `cookingTime`.
The average cost of the recipe in a property named `cost` where the possible values are `low`, `medium` or `high`.
The amount of of dishes that result from the recipe in a property named `people`.